### ISSUE TITLE
How to join the server.

### ISSUE THREAD

**Issue by EdQinux** [imperialwool/HuggingCraft#1]
I have setup the docker in hugging face, like in the instructions but can't figure out how to join the server.

**Comment by shaderw0lf** [comment]
1. Go to ngrok's dashboard
2. Go to tunnels -> agents
3. You will see active agent. Click on it
4. You will see agent's ip, region and tunnel what ngrok made to connect to server. This is ip of server <img width="1440" alt="Снимок экрана 2024-04-12 в 14 11 56" src="https://github.com/imperialwool/HuggingCraft/assets/55358751/0a8c97f4-8106-4aab-88ad-5b946bd2dc8f">
5. Enter this ip as minecraft server's ip (without tcp://)
6. Play

**Comment by shaderw0lf** [comment]
I will add this to instructions
